clc;
close all;
clear;
N=256;
I=phantom(N);
delta=pi/180;
theta=0:1:179;
theta_num=length(theta);
P=radon(I,theta);
[mm,nn]=size(P);
e=floor((mm-N-1)/2+1)+1;
P=P(e:N+e-1,:);
P1=reshape(P,N,theta_num);
rec=medfuncBackprojection(theta_num,N,P1,delta);
figure;
imshow(I,[]),title('原始图像');
figure;
imshow(rec,[]),title('直接反投影重建图像');